DROP TABLE IF EXISTS users, requests, items, comments, bookings;

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    CONSTRAINT EMAIL_UNIQUE UNIQUE (email),
    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR(1000) NOT NULL,
    requestor_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_request PRIMARY KEY (request_id)
);

CREATE TABLE IF NOT EXISTS items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    is_available BOOLEAN,
    owner_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    request_id BIGINT REFERENCES requests (request_id) ON DELETE CASCADE,
    CONSTRAINT pk_item PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text VARCHAR(1000) NOT NULL,
    item_id BIGINT REFERENCES items (item_id) ON DELETE CASCADE,
    author_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comments PRIMARY KEY (comment_id)
);

CREATE TABLE IF NOT EXISTS bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id BIGINT REFERENCES items (item_id) ON DELETE CASCADE,
    booker_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    status VARCHAR(10),
    CONSTRAINT pk_booking PRIMARY KEY (booking_id)
);